;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-brace
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-hungry-delete-forward
        c-indent-line-or-region
        drag-stuff-down
        gcm-scroll-down
        gcm-scroll-up
        hungry-delete-backward
        hungry-delete-forward
        ignore
        indent-for-tab-command
        kill-region
        kill-visual-line
        kmacro-end-or-call-macro
        markdown-outdent-or-delete
        my-open-init-el
        nuke-line
        nxml-electric-slash
        org-kill-line
        org-self-insert-command
        org-yank
        overwrite-mode
        smart-beginning-of-line
        xref-pop-marker-stack
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        compile-goto-error
        counsel-yank-pop
        duplicate-line-or-region
        gud-tooltip-mouse-motion
        help-for-help
        ido-find-file
        mouse-set-region
        my-compile
        my-open-cmany-el
        my-open-init-el
        my-recompile
        smex
        ))
