;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-hungry-delete-forward
        hungry-delete-forward
        indent-for-tab-command
        kill-region
        overwrite-mode
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        compile-goto-error
        counsel-yank-pop
        gud-tooltip-mouse-motion
        my-open-init-el
        my-open-cmany-el
        my-recompile
        ))
