;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-colon
        c-electric-lt-gt
        c-electric-paren
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-hungry-delete-forward
        gcm-scroll-down
        gcm-scroll-up
        hungry-delete-backward
        hungry-delete-forward
        kill-region
        my-open-init-el
        overwrite-mode
        smart-beginning-of-line
        yaml-electric-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        gud-tooltip-mouse-motion
        my-recompile
        ))
