(setq
 elfeed-feeds
 '(
   ;; history
   ("https://martyrmade.substack.com/feed/" history)
   ("https://anderssonerik.substack.com/feed/" history)
   ("https://unlimitedhangout.com/feed/" politics)
   ("https://courtenayturner.com/feed/" politics)
   ;; life
   ("http://modernstoicism.com/feed/" life)  ;;<outline type="rss" text="Modern Stoicism" title="Modern Stoicism" xmlUrl="http://modernstoicism.com/feed/" htmlUrl="https://modernstoicism.com"/>
   ("http://jamesaltucher.tumblr.com/rss" life) ;;<outline type="rss" text="James Altucher" title="James Altucher" xmlUrl="http://jamesaltucher.tumblr.com/rss" htmlUrl="https://jamesaltucher.tumblr.com/"/>
   ("http://destrezadasduvidas.blogspot.com/feeds/posts/default" life) ;;<outline type="rss" text="A Destreza das Dúvidas" title="A Destreza das Dúvidas" xmlUrl="http://destrezadasduvidas.blogspot.com/feeds/posts/default" htmlUrl="http://destrezadasduvidas.blogspot.com/"/>
   ("http://feeds.feedburner.com/jamesaltucher" life) ;;<outline type="rss" text="James Altucher" title="James Altucher" xmlUrl="http://feeds.feedburner.com/jamesaltucher" htmlUrl="https://jamesaltucher.com"/>
   ("http://feeds2.feedburner.com/TheArtOfManliness" life) ;;<outline type="rss" text="The Art of Manliness" title="The Art of Manliness" xmlUrl="http://feeds2.feedburner.com/TheArtOfManliness" htmlUrl="https://www.artofmanliness.com/"/>
   ("http://www.askamanager.org/feed" life) ;;<outline type="rss" text="Ask a Manager" title="Ask a Manager" xmlUrl="http://www.askamanager.org/feed" htmlUrl="https://www.askamanager.org/"/>
   ("http://feeds.feedburner.com/thesimpledollar" life) ;;<outline type="rss" text="The Simple Dollar" title="The Simple Dollar" xmlUrl="http://feeds.feedburner.com/thesimpledollar" htmlUrl="https://www.thesimpledollar.com"/>
   ("https://futiletributavel.blogs.sapo.pt/data/rss" life) ;;<outline type="rss" text="Casada, fútil, quotidiana e tributável" title="Casada, fútil, quotidiana e tributável" xmlUrl="https://futiletributavel.blogs.sapo.pt/data/rss" htmlUrl="https://futiletributavel.blogs.sapo.pt/"/>
   ("http://jordanbpeterson.com/feed/" life) ;;<outline type="rss" text="Jordan Peterson" title="Jordan Peterson" xmlUrl="http://jordanbpeterson.com/feed/" htmlUrl="https://www.jordanbpeterson.com"/>
   ("http://malomil.blogspot.com/feeds/posts/default" life) ;;<outline type="rss" text="Malomil" title="Malomil" xmlUrl="http://malomil.blogspot.com/feeds/posts/default" htmlUrl="http://malomil.blogspot.com/"/>
   ("https://perderbem.blogs.sapo.pt/data/atom" life) ;;<outline type="rss" text="PERDER BEM por Filipe Nunes Vicente" title="PERDER BEM por Filipe Nunes Vicente" xmlUrl="https://perderbem.blogs.sapo.pt/data/atom" htmlUrl="https://perderbem.blogs.sapo.pt/"/>
   ("http://academyofideas.com/feed/" life) ;;<outline type="rss" text="Academy of Ideas" title="Academy of Ideas" xmlUrl="http://academyofideas.com/feed/" htmlUrl="https://academyofideas.com"/>

   ("https://skipboring.com/web-stories/feed/" culture) ;;<outline type="rss" text="Stories – Skip Boring" title="Stories – Skip Boring" xmlUrl="https://skipboring.com/web-stories/feed/" htmlUrl="https://skipboring.com"/>
   ("https://skipboring.com/feed/" culture) ;;<outline type="rss" text="Skip Boring" title="Skip Boring" xmlUrl="https://skipboring.com/feed/" htmlUrl="https://skipboring.com"/>
   ("https://medium.com/feed/@nntaleb" culture) ;;<outline type="rss" text="Stories by Nassim Nicholas Taleb on Medium" title="Stories by Nassim Nicholas Taleb on Medium" xmlUrl="https://medium.com/feed/@nntaleb" htmlUrl="https://medium.com/@nntaleb?source=rss-f138bf5466fe------2"/>
   ("http://www.forbes.com/sites/rogerscruton/feed/" culture) ;;<outline type="rss" text="Roger Scruton Culture Matters" title="Culture Matters" xmlUrl="http://www.forbes.com/sites/rogerscruton/feed/" htmlUrl="http://www.forbes.com/sites/rogerscruton/"/>
   ("http://roger-scruton.blogspot.com/feeds/posts/default" culture) ;;<outline type="rss" text="Roger Scruton" title="Roger Scruton" xmlUrl="http://roger-scruton.blogspot.com/feeds/posts/default" htmlUrl="http://roger-scruton.blogspot.com/"/>
   ("http://www.rogerscruton.com/articles.feed?type=rss" culture) ;;<outline type="rss" text="Roger Scruton Articles" title="Articles" xmlUrl="http://www.rogerscruton.com/articles.feed?type=rss" htmlUrl="http://www.rogerscruton.com/articles.html"/>

   ("http://www.acting-man.com/?feed=rss2" economics) ;;<outline type="rss" text="Acting Man" title="www.acting-man.com/?feed=rss2" xmlUrl="http://www.acting-man.com/?feed=rss2" htmlUrl="https://acting-man.com"/>
   ("http://cafehayek.typepad.com/hayek/atom.xml" economics) ;;<outline type="rss" text="Cafe Hayek" title="Cafe Hayek" xmlUrl="http://cafehayek.typepad.com/hayek/atom.xml" htmlUrl="https://cafehayek.com/"/>
   ("https://betonit.substack.com/feed" economics) ;;<outline type="rss" text="Bet On It" title="Bet On It" xmlUrl="https://betonit.substack.com/feed" htmlUrl="https://www.betonit.ai"/>
   ("http://feeds.fee.org/FEE-Freeman" economics) ;;<outline type="rss" text="from FEE" title="from FEE" xmlUrl="http://feeds.fee.org/FEE-Freeman" htmlUrl="https://fee.org/articles/"/>
   ("https://www.econlib.org/author/bcaplan/feed/" economics) ;;<outline type="rss" text="Bryan Caplan, Author at Econlib" title="Bryan Caplan, Author at Econlib" xmlUrl="https://www.econlib.org/author/bcaplan/feed/" htmlUrl="https://www.econlib.org/author/bcaplan/"/>

   ("http://tempocontado.blogspot.com/feeds/posts/default" literature) ;;<outline type="rss" text="TEMPO CONTADO" title="TEMPO CONTADO" xmlUrl="http://tempocontado.blogspot.com/feeds/posts/default" htmlUrl="https://tempocontado.blogspot.com/"/>
   ("http://origemdasespecies.blogs.sapo.pt/data/rss" literature) ;;<outline type="rss" text="A Origem das Espécies" title="A Origem das Espécies" xmlUrl="http://origemdasespecies.blogs.sapo.pt/data/rss" htmlUrl="https://origemdasespecies.blogs.sapo.pt/"/>

   ("http://feeds.feedburner.com/ScottHanselman"  prog) ;;<outline type="rss" text="Scott Hanselman's Blog" title="Scott Hanselman's Blog" xmlUrl="http://feeds.feedburner.com/ScottHanselman" htmlUrl="https://www.hanselman.com/blog/"/>
   ("http://odinthenerd.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="C++ Metaprogramming" title="C++ Metaprogramming" xmlUrl="http://odinthenerd.blogspot.com/feeds/posts/default" htmlUrl="http://odinthenerd.blogspot.com/"/>
   ("http://scottmeyers.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="The View from Aristeia" title="The View from Aristeia" xmlUrl="http://scottmeyers.blogspot.com/feeds/posts/default" htmlUrl="http://scottmeyers.blogspot.com/"/>
   ("http://eli.thegreenplace.net/feed/"  prog) ;;<outline type="rss" text="Eli Bendersky's website" title="Eli Bendersky's website" xmlUrl="http://eli.thegreenplace.net/feed/" htmlUrl="https://eli.thegreenplace.net/"/>
   ("http://timothylottes.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="Timothy Lottes" title="Timothy Lottes" xmlUrl="http://timothylottes.blogspot.com/feeds/posts/default" htmlUrl="http://timothylottes.blogspot.com/"/>
   ("http://blog.rust-lang.org/feed.xml"  prog) ;;<outline type="rss" text="Rust Blog" title="Rust Blog" xmlUrl="http://blog.rust-lang.org/feed.xml" htmlUrl="https://blog.rust-lang.org/"/>
   ("http://preney.ca/paul/feed/"  prog) ;;<outline type="rss" text="pseudorandom noise" title="pseudorandom noise" xmlUrl="http://preney.ca/paul/feed/" htmlUrl="https://www.preney.ca/paul"/>
   ("https://sigsegv.me/feed/"  prog) ;;<outline type="rss" text="SIGSEGV" title="SIGSEGV" xmlUrl="https://sigsegv.me/feed/" htmlUrl="https://sigsegv.me"/>
   ("http://moderncpp.com/feed/"  prog) ;;<outline type="rss" text="C++/WinRT" title="C++/WinRT" xmlUrl="http://moderncpp.com/feed/" htmlUrl="https://moderncpp.com"/>
   ("http://embeddedgurus.com/stack-overflow/feed/"  prog) ;;<outline type="rss" text="Stack Overflow" title="Stack Overflow" xmlUrl="http://embeddedgurus.com/stack-overflow/feed/" htmlUrl="https://embeddedgurus.com/stack-overflow"/>
   ("http://richg42.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="Richard Geldreich's Blog" title="Richard Geldreich's Blog" xmlUrl="http://richg42.blogspot.com/feeds/posts/default" htmlUrl="http://richg42.blogspot.com/"/>
   ("https://interrupt.memfault.com/blog/feed.xml"  prog) ;;<outline type="rss" text="Interrupt" title="Interrupt" xmlUrl="https://interrupt.memfault.com/blog/feed.xml" htmlUrl="https://interrupt.memfault.com/"/>
   ("http://casual-effects.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="Casual Effects" title="Casual Effects" xmlUrl="http://casual-effects.blogspot.com/feeds/posts/default" htmlUrl="http://casual-effects.blogspot.com/"/>
   ("http://blog.feabhas.com/feed/rss2/"  prog) ;;<outline type="rss" text="Sticky Bits – Powered by Feabhas" title="Sticky Bits – Powered by Feabhas" xmlUrl="http://blog.feabhas.com/feed/rss2/" htmlUrl="https://blog.feabhas.com/"/>
   ("https://nativecoding.wordpress.com/feed/"  prog) ;;<outline type="rss" text="NativeCoding" title="NativeCoding" xmlUrl="https://nativecoding.wordpress.com/feed/" htmlUrl="https://nativecoding.wordpress.com"/>
   ("http://bartoszmilewski.wordpress.com/feed/"  prog) ;;<outline type="rss" text="Bartosz Milewski's Programming Cafe" title="Bartosz Milewski's Programming Cafe" xmlUrl="http://bartoszmilewski.wordpress.com/feed/" htmlUrl="https://bartoszmilewski.com"/>
   ("http://www.goldsborough.me/feed.xml"  prog) ;;<outline type="rss" text="Peter Goldsborough" title="Peter Goldsborough" xmlUrl="http://www.goldsborough.me/feed.xml" htmlUrl="http://www.goldsborough.me/"/>
   ("http://pocoproject.org/blog/?feed=rss2"  prog) ;;<outline type="rss" text="POCO C++ Libraries Blog" title="POCO C++ Libraries Blog" xmlUrl="http://pocoproject.org/blog/?feed=rss2" htmlUrl="https://pocoproject.org/blog"/>
   ("http://akrzemi1.wordpress.com/feed/"  prog) ;;<outline type="rss" text="Andrzej's C++ blog" title="Andrzej's C++ blog" xmlUrl="http://akrzemi1.wordpress.com/feed/" htmlUrl="https://akrzemi1.wordpress.com"/>
   ("http://www.realtimerendering.com/blog/feed/"  prog) ;;<outline type="rss" text="Real-Time Rendering" title="Real-Time Rendering" xmlUrl="http://www.realtimerendering.com/blog/feed/" htmlUrl="https://www.realtimerendering.com/blog"/>
   ("http://feeds.feedburner.com/KhronosorgNews"  prog) ;;<outline type="rss" text="News" title="News" xmlUrl="http://feeds.feedburner.com/KhronosorgNews" htmlUrl="http://www.khronos.org"/>
   ("http://c0de517e.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="C0DE517E" title="C0DE517E" xmlUrl="http://c0de517e.blogspot.com/feeds/posts/default" htmlUrl="http://c0de517e.blogspot.com/"/>
   ("http://ericniebler.com/feed/"  prog) ;;<outline type="rss" text="Eric Niebler" title="Eric Niebler" xmlUrl="http://ericniebler.com/feed/" htmlUrl="https://ericniebler.com"/>
   ("http://mortoray.com/feed/"  prog) ;;<outline type="rss" text="Musing Mortoray" title="Musing Mortoray" xmlUrl="http://mortoray.com/feed/" htmlUrl="https://mortoray.com/"/>
   ("http://molecularmusings.wordpress.com/feed/"  prog) ;;<outline type="rss" text="Molecular Musings" title="Molecular Musings" xmlUrl="http://molecularmusings.wordpress.com/feed/" htmlUrl="https://blog.molecular-matters.com"/>
   ("http://pzurita.wordpress.com/feed/"  prog) ;;<outline type="rss" text="Pablo Zurita's blog" title="Pablo Zurita's blog" xmlUrl="http://pzurita.wordpress.com/feed/" htmlUrl="https://pzurita.wordpress.com"/>
   ("http://blogs.msdn.com/vcblog/rss.xml"  prog) ;;<outline type="rss" text="C++ Team Blog" title="C++ Team Blog" xmlUrl="http://blogs.msdn.com/vcblog/rss.xml" htmlUrl="https://devblogs.microsoft.com/cppblog/"/>
   ("http://feeds.feedburner.com/TheGeeksOf3d"  prog) ;;<outline type="rss" text="Geeks3D" title="Geeks3D" xmlUrl="http://feeds.feedburner.com/TheGeeksOf3d" htmlUrl="https://www.geeks3d.com"/>
   ("http://rmartinho.github.com/rss.xml"  prog) ;;<outline type="rss" text="Flaming Dangerzone" title="Flaming Dangerzone" xmlUrl="http://rmartinho.github.com/rss.xml" htmlUrl="http://flamingdangerzone.com/"/>
   ("http://3dgep.com/?feed=rss2"  prog) ;;<outline type="rss" text="3D Game Engine Programming" title="3D Game Engine Programming" xmlUrl="http://3dgep.com/?feed=rss2" htmlUrl="https://www.3dgep.com/"/>
   ("https://thehftguy.wordpress.com/feed/"  prog) ;;<outline type="rss" text="The HFT Guy" title="The HFT Guy" xmlUrl="https://thehftguy.wordpress.com/feed/" htmlUrl="https://thehftguy.com"/>
   ("http://www.murrayc.com/feed/"  prog) ;;<outline type="rss" text="Murray's Blog" title="Murray's Blog" xmlUrl="http://www.murrayc.com/feed/" htmlUrl="https://www.murrayc.com"/>
   ("http://www.embedded.com/Rss/All"  prog) ;;<outline type="rss" text="All Articles" title="All Articles" xmlUrl="http://www.embedded.com/Rss/All" htmlUrl="http://www.embedded.com"/>
   ("http://www.meetingcpp.com/blogen.xml"  prog) ;;<outline type="rss" text="Meeting C++ blog" title="Meeting C++ blog" xmlUrl="http://www.meetingcpp.com/blogen.xml" htmlUrl="https://www.meetingcpp.com/"/>
   ("http://feeds.feedburner.com/LostInTheTriangles"  prog) ;;<outline type="rss" text="Aras' website" title="Aras' website" xmlUrl="http://feeds.feedburner.com/LostInTheTriangles" htmlUrl="https://aras-p.info/"/>
   ("http://www.codercorner.com/blog/?feed=rss2"  prog) ;;<outline type="rss" text="Coder Corner" title="Coder Corner" xmlUrl="http://www.codercorner.com/blog/?feed=rss2" htmlUrl="http://www.codercorner.com/blog"/>
   ("http://jmabille.github.io/atom.xml"  prog) ;;<outline type="rss" text="The C++ scientist" title="The C++ scientist" xmlUrl="http://jmabille.github.io/atom.xml" htmlUrl="http://jmabille.github.io/"/>
   ("http://www.justsoftwaresolutions.co.uk/index.rss"  prog) ;;<outline type="rss" text="Just Software Solutions Blog" title="Just Software Solutions Blog" xmlUrl="http://www.justsoftwaresolutions.co.uk/index.rss" htmlUrl="http://www.justsoftwaresolutions.co.uk/blog/"/>
   ("http://martinfowler.com/bliki/bliki.atom"  prog) ;;<outline type="rss" text="Martin Fowler" title="Martin Fowler" xmlUrl="http://martinfowler.com/bliki/bliki.atom" htmlUrl="https://martinfowler.com"/>
   ("http://cpptruths.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="C++ Truths" title="C++ Truths" xmlUrl="http://cpptruths.blogspot.com/feeds/posts/default" htmlUrl="http://cpptruths.blogspot.com/"/>
   ("http://gpuopen.com/feed/"  prog) ;;<outline type="rss" text="AMD GPUOpen" title="AMD GPUOpen" xmlUrl="http://gpuopen.com/feed/" htmlUrl="https://gpuopen.com/"/>
   ("http://number-none.com/blow/blog/feed.xml"  prog) ;;<outline type="rss" text="Jonathan Blow's blog" title="Jonathan Blow's blog" xmlUrl="http://number-none.com/blow/blog/feed.xml" htmlUrl="http://number-none.com/blow/blog/"/>
   ("http://blog.mmacklin.com/feed/"  prog) ;;<outline type="rss" text="Miles Macklin" title="Miles Macklin" xmlUrl="http://blog.mmacklin.com/feed/" htmlUrl="http://blog.mmacklin.com/"/>
   ("http://animationphysics.wordpress.com/feed/"  prog) ;;<outline type="rss" text="Physics-Based Animation" title="Physics-Based Animation" xmlUrl="http://animationphysics.wordpress.com/feed/" htmlUrl="https://www.physicsbasedanimation.com"/>
   ("http://isocpp.org/blog/rss"  prog) ;;<outline type="rss" text="Standard C++" title="Standard C++" xmlUrl="http://isocpp.org/blog/rss" htmlUrl="http://isocpp.org/blog"/>
   ("http://feeds.feedburner.com/gpgpuorg"  prog) ;;<outline type="rss" text="GPGPU" title="GPGPU" xmlUrl="http://feeds.feedburner.com/gpgpuorg" htmlUrl="http://gpgpu.org"/>
   ("http://learnlinuxconcepts.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="LINUX KERNEL INTERNALS" title="LINUX KERNEL INTERNALS" xmlUrl="http://learnlinuxconcepts.blogspot.com/feeds/posts/default" htmlUrl="https://learnlinuxconcepts.blogspot.com/"/>
   ("http://mynameismjp.wordpress.com/feed/"  prog) ;;<outline type="rss" text="The Danger Zone" title="The Danger Zone" xmlUrl="http://mynameismjp.wordpress.com/feed/" htmlUrl="https://mynameismjp.wordpress.com"/>
   ("http://feeds.feedburner.com/daniel-lemire/atom"  prog) ;;<outline type="rss" text="Daniel Lemire's blog" title="Daniel Lemire's blog" xmlUrl="http://feeds.feedburner.com/daniel-lemire/atom" htmlUrl="https://lemire.me/blog"/>
   ("http://cplusplusmusings.wordpress.com/feed/"  prog) ;;<outline type="rss" text="Marshall's C++ Musings" title="Marshall's C++ Musings" xmlUrl="http://cplusplusmusings.wordpress.com/feed/" htmlUrl="https://cplusplusmusings.wordpress.com"/>
   ("http://blog.regehr.org/feed"  prog) ;;<outline type="rss" text="Embedded in Academia" title="Embedded in Academia" xmlUrl="http://blog.regehr.org/feed" htmlUrl="https://blog.regehr.org"/>
   ("https://developer.nvidia.com/blog/5007/feed"  prog) ;;<outline type="rss" text="NVIDIA Developer Blog" title="NVIDIA Developer Blog" xmlUrl="https://developer.nvidia.com/blog/5007/feed" htmlUrl="https://developer.nvidia.com/"/>
   ("https://betterembsw.blogspot.com/feeds/posts/default?alt=rss"  prog) ;;<outline type="rss" text="Better Embedded System SW" title="Better Embedded System SW" xmlUrl="https://betterembsw.blogspot.com/feeds/posts/default?alt=rss" htmlUrl="http://betterembsw.blogspot.com/"/>
   ("https://www.computerenhance.com/feed"  prog) ;;<outline type="rss" text="Computer, Enhance!" title="Computer, Enhance!" xmlUrl="https://www.computerenhance.com/feed" htmlUrl="https://www.computerenhance.com"/>
   ("http://www.reedbeta.com/blog/feed/"  prog) ;;<outline type="rss" text="Nathan Reed’s coding blog" title="Nathan Reed’s coding blog" xmlUrl="http://www.reedbeta.com/blog/feed/" htmlUrl="https://www.reedbeta.com/"/>
   ("http://renderingpipeline.com/feed/"  prog) ;;<outline type="rss" text="RenderingPipeline" title="RenderingPipeline" xmlUrl="http://renderingpipeline.com/feed/" htmlUrl="http://renderingpipeline.com"/>
   ("http://blog.demofox.org/feed/"  prog) ;;<outline type="rss" text="The blog at the bottom of the sea" title="The blog at the bottom of the sea" xmlUrl="http://blog.demofox.org/feed/" htmlUrl="https://blog.demofox.org"/>
   ("http://blogs.msdn.com/DirectX/rss.xml"  prog) ;;<outline type="rss" text="DirectX Developer Blog" title="DirectX Developer Blog" xmlUrl="http://blogs.msdn.com/DirectX/rss.xml" htmlUrl="https://devblogs.microsoft.com/directx/"/>
   ("http://arne-mertz.de/feed/"  prog) ;;<outline type="rss" text="Simplify C++!" title="Simplify C++!" xmlUrl="http://arne-mertz.de/feed/" htmlUrl="https://arne-mertz.de/"/>
   ("http://seanmiddleditch.com/rss/"  prog) ;;<outline type="rss" text="Sean Middleditch Psychic Readings" title="Sean Middleditch Psychic Readings" xmlUrl="http://seanmiddleditch.com/rss/" htmlUrl="https://seanmiddleditch.com/"/>
   ("http://codecraft.co/feed/"  prog) ;;<outline type="rss" text="Codecraft" title="Codecraft" xmlUrl="http://codecraft.co/feed/" htmlUrl="https://codecraft.co"/>
   ("http://home.comcast.net/~tom_forsyth/blog.wiki.xml"  prog) ;;<outline type="rss" text="TomF's Tech Blog" title="TomF's Tech Blog" xmlUrl="http://home.comcast.net/~tom_forsyth/blog.wiki.xml" htmlUrl="http://eelpi.gotdns.org/blog.wiki.html"/>
   ("http://raytracey.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="Ray Tracey's blog" title="Ray Tracey's blog" xmlUrl="http://raytracey.blogspot.com/feeds/posts/default" htmlUrl="http://raytracey.blogspot.com/"/>
   ("http://roar11.com/feed/"  prog) ;;<outline type="rss" text="WillP GFX" title="WillP GFX" xmlUrl="http://roar11.com/feed/" htmlUrl="https://willpgfx.com/"/>
   ("http://jobtipsforgeeks.com/feed/"  prog) ;;<outline type="rss" text="Job Tips For Geeks" title="Job Tips For Geeks" xmlUrl="http://jobtipsforgeeks.com/feed/" htmlUrl="https://jobtipsforgeeks.com"/>
   ("http://feeds.feedburner.com/amd/play"  prog) ;;<outline type="rss" text="AMD Gaming" title="AMD Gaming" xmlUrl="http://feeds.feedburner.com/amd/play" htmlUrl="http://community.amd.com/community/amd-blogs/amd-gaming/blog"/>
   ("http://feeds.feedburner.com/codinghorror/"  prog) ;;<outline type="rss" text="Coding Horror" title="Coding Horror" xmlUrl="http://feeds.feedburner.com/codinghorror/" htmlUrl="https://blog.codinghorror.com/"/>
   ("http://moodycamel.com/blog/feed"  prog) ;;<outline type="rss" text="moodycamel.com blog" title="moodycamel.com blog" xmlUrl="http://moodycamel.com/blog/feed" htmlUrl="http://moodycamel.com/blog"/>
   ("http://feeds.feedburner.com/g-truc"  prog) ;;<outline type="rss" text="G-Truc Creation - Archives" title="G-Truc Creation - Archives" xmlUrl="http://feeds.feedburner.com/g-truc" htmlUrl="http://www.g-truc.net/index.html"/>
   ("https://www.preney.ca/paul/comments/feed"  prog) ;;<outline type="rss" text="pseudorandom noise » Comments Feed" title="pseudorandom noise » Comments Feed" xmlUrl="https://www.preney.ca/paul/comments/feed" htmlUrl="https://www.preney.ca/paul"/>
   ("http://herbsutter.com/feed/"  prog) ;;<outline type="rss" text="Sutter’s Mill" title="Sutter’s Mill" xmlUrl="http://herbsutter.com/feed/" htmlUrl="https://herbsutter.com"/>
   ("http://blogs.unity3d.com/feed/"  prog) ;;<outline type="rss" text="Unity Blog RSS Feed" title="Unity Blog RSS Feed" xmlUrl="http://blogs.unity3d.com/feed/" htmlUrl="https://unity.com"/>
   ("http://diaryofagraphicsprogrammer.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="Diary of a Graphics Programmer" title="Diary of a Graphics Programmer" xmlUrl="http://diaryofagraphicsprogrammer.blogspot.com/feeds/posts/default" htmlUrl="http://diaryofagraphicsprogrammer.blogspot.com/"/>
   ("http://balau82.wordpress.com/feed/"  prog) ;;<outline type="rss" text="Freedom Embedded" title="Freedom Embedded" xmlUrl="http://balau82.wordpress.com/feed/" htmlUrl="https://balau82.wordpress.com"/>
   ("https://www.reddit.com/r/vulkan/.rss"  prog) ;;<outline type="rss" text="Vulkan – Khronos' API for High" title="Vulkan – Khronos' API for High" xmlUrl="https://www.reddit.com/r/vulkan/.rss" htmlUrl="https://www.reddit.com/r/vulkan/"/>
   ("http://ithare.com/rssfeed/"  prog) ;;<outline type="rss" text="IT Hare on Soft.ware" title="IT Hare on Soft.ware" xmlUrl="http://ithare.com/rssfeed/" htmlUrl="http://ithare.com"/>
   ("http://bitsquid.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="bitsquid: development blog" title="bitsquid: development blog" xmlUrl="http://bitsquid.blogspot.com/feeds/posts/default" htmlUrl="http://bitsquid.blogspot.com/"/>
   ("http://codesynthesis.com/~boris/blog/feed/"  prog) ;;<outline type="rss" text="A Sense of Design" title="A Sense of Design" xmlUrl="http://codesynthesis.com/~boris/blog/feed/" htmlUrl="https://codesynthesis.com/~boris/blog/"/>
   ("http://anteru.net/feed/"  prog) ;;<outline type="rss" text="Anteru's blog" title="Anteru's blog" xmlUrl="http://anteru.net/feed/" htmlUrl="https://anteru.net"/>
   ("http://preshing.com/feed"  prog) ;;<outline type="rss" text="Preshing on Programming" title="Preshing on Programming" xmlUrl="http://preshing.com/feed" htmlUrl="https://preshing.com/"/>
   ("http://www.vitorian.com/x1/feed"  prog) ;;<outline type="rss" text="Vitorian LLC" title="Vitorian LLC" xmlUrl="http://www.vitorian.com/x1/feed" htmlUrl="http://www.vitorian.com"/>
   ("http://bannalia.blogspot.com/feeds/posts/default"  prog) ;;<outline type="rss" text="Bannalia: trivial notes on themes diverse" title="Bannalia: trivial notes on themes diverse" xmlUrl="http://bannalia.blogspot.com/feeds/posts/default" htmlUrl="http://bannalia.blogspot.com/"/>

   ("https://unrealdevtk.wordpress.com/feed/" gamedev) ;;<outline type="rss" text="TK's Dev Blog" title="TK's Dev Blog" xmlUrl="https://unrealdevtk.wordpress.com/feed/" htmlUrl="https://unrealdevtk.wordpress.com"/>
   ("https://www.unrealengine.com/rss" gamedev) ;;<outline type="rss" text="Unreal Engine - News, Developer Interviews, Spotlights, Tech Blogs" title="Unreal Engine - News, Developer Interviews, Spotlights, Tech Blogs" xmlUrl="https://www.unrealengine.com/rss" htmlUrl="https://www.unrealengine.com/rss"/>
   ("http://3dgep.com/?feed=rss2" gamedev) ;;<outline type="rss" text="3D Game Engine Programming" title="3D Game Engine Programming" xmlUrl="http://3dgep.com/?feed=rss2" htmlUrl="https://www.3dgep.com/"/>
   ("http://feeds.feedburner.com/GamasutraFeatureArticles/" gamedev) ;;<outline type="rss" text="Gamasutra" title="Gamasutra" xmlUrl="http://feeds.feedburner.com/GamasutraFeatureArticles/" htmlUrl="http://www.gamasutra.com/newswire"/>
   ("http://yosoygames.com.ar/wp/feed/" gamedev) ;;<outline type="rss" text="Yosoygames" title="Yosoygames" xmlUrl="http://yosoygames.com.ar/wp/feed/" htmlUrl="https://www.yosoygames.com.ar/wp"/>
   ("http://www.gamesindustry.biz/rss/gamesindustry_news_feed.rss" gamedev) ;;<outline type="rss" text="GamesIndustry.biz Latest Articles Feed" title="GamesIndustry.biz Latest Articles Feed" xmlUrl="http://www.gamesindustry.biz/rss/gamesindustry_news_feed.rss" htmlUrl="https://www.gamesindustry.biz/feed"/>
   ("http://www.gamasutra.com/blogs/rss-expert/" gamedev) ;;<outline type="rss" text="Gamasutra.com" title="Gamasutra.com" xmlUrl="http://www.gamasutra.com/blogs/rss-expert/" htmlUrl="https://www.gamasutra.com/blogs/expert/"/>
   ("http://joostdevblog.blogspot.com/feeds/posts/default" gamedev) ;;<outline type="rss" text="Joost's Dev Blog" title="Joost's Dev Blog" xmlUrl="http://joostdevblog.blogspot.com/feeds/posts/default" htmlUrl="http://joostdevblog.blogspot.com/"/>
   ("https://laissez-faire.ch/en/rss/blog/" gamedev) ;;<outline type="rss" text="Laissez-faire - Blog" title="Laissez-faire - Blog" xmlUrl="https://laissez-faire.ch/en/rss/blog/" htmlUrl="https://laissez-faire.ch/"/>

   ("http://traderfeed.blogspot.com/feeds/posts/default" finance) ;;<outline type="rss" text="TraderFeed" title="TraderFeed" xmlUrl="http://traderfeed.blogspot.com/feeds/posts/default" htmlUrl="http://traderfeed.blogspot.com/"/>
   ("http://gekkoquant.com/feed/" finance) ;;<outline type="rss" text="Gekko Quant – Quantitative Trading" title="Gekko Quant – Quantitative Trading" xmlUrl="http://gekkoquant.com/feed/" htmlUrl="http://gekkoquant.com"/>
   ("https://tomluongo.me/feed/" finance) ;;<outline type="rss" text="Gold Goats 'n Guns" title="Gold Goats 'n Guns" xmlUrl="https://tomluongo.me/feed/" htmlUrl="https://tomluongo.me/"/>
   ("http://www.zerohedge.com/rss.xml" finance) ;;<outline type="rss" text="Zero Hedge" title="Zero Hedge" xmlUrl="http://www.zerohedge.com/rss.xml" htmlUrl="http://www.zerohedge.com"/>
   ("http://quantifiableedges.com/feed/" finance) ;;<outline type="rss" text="Quantifiable Edges" title="Quantifiable Edges" xmlUrl="http://quantifiableedges.com/feed/" htmlUrl="https://quantifiableedges.com"/>
   ("http://quantstart.com/feed" finance) ;;<outline type="rss" text="QuantStart.com" title="QuantStart.com" xmlUrl="http://quantstart.com/feed" htmlUrl="http://quantstart.com/"/>
   ("http://www.followingthetrend.com/feed/" finance) ;;<outline type="rss" text="Following the Trend" title="Following the Trend" xmlUrl="http://www.followingthetrend.com/feed/" htmlUrl="https://www.followingthetrend.com"/>
   ("http://blog.alphaarchitect.com/feed/" finance) ;;<outline type="rss" text="Alpha Architect" title="Alpha Architect" xmlUrl="http://blog.alphaarchitect.com/feed/" htmlUrl="https://alphaarchitect.com/"/>
   ("http://dynamichedge.com/feed/" finance) ;;<outline type="rss" text="Dynamic Hedge" title="Dynamic Hedge" xmlUrl="http://dynamichedge.com/feed/" htmlUrl="http://www.dynamichedge.com"/>
   ("http://feeds.feedburner.com/johnmauldin/newsletters" finance) ;;<outline type="rss" text="Mauldin Newsletters" title="Mauldin Newsletters" xmlUrl="http://feeds.feedburner.com/johnmauldin/newsletters" htmlUrl="https://www.mauldineconomics.com/newsletters"/>
   ("http://feeds.feedburner.com/autrasy-blog" finance) ;;<outline type="rss" text="Au.Tra.Sy blog – Automated trading System" title="Au.Tra.Sy blog – Automated trading System" xmlUrl="http://feeds.feedburner.com/autrasy-blog" htmlUrl="http://www.automated-trading-system.com"/>
   ("http://epchan.blogspot.com/feeds/posts/default" finance) ;;<outline type="rss" text="Quantitative Trading" title="Quantitative Trading" xmlUrl="http://epchan.blogspot.com/feeds/posts/default" htmlUrl="http://epchan.blogspot.com/"/>
   ("http://bitcoinism.liberty.me/feed/" finance) ;;<outline type="rss" text="B I T C O I N I S M" title="B I T C O I N I S M" xmlUrl="http://bitcoinism.liberty.me/feed/" htmlUrl="https://bitcoinism.liberty.me"/>
   ("http://abnormalreturns.com/feed/" finance) ;;<outline type="rss" text="Abnormal Returns" title="Abnormal Returns" xmlUrl="http://abnormalreturns.com/feed/" htmlUrl="https://abnormalreturns.com"/>
   ("http://www.stuartreid.co.za/feed/" finance) ;;<outline type="rss" text="stuartreid.co.za" title="stuartreid.co.za" xmlUrl="http://www.stuartreid.co.za/feed/" htmlUrl="https://stuartreid.co.za"/>
   ("http://www.amsterdamtrader.com/feed" finance) ;;<outline type="rss" text="Amsterdamtrader" title="Amsterdamtrader" xmlUrl="http://www.amsterdamtrader.com/feed" htmlUrl="https://www.amsterdamtrader.com"/>
   ("http://www.quantatrisk.com/feed/" finance) ;;<outline type="rss" text="Øuant at Risk" title="Øuant at Risk" xmlUrl="http://www.quantatrisk.com/feed/" htmlUrl="https://quantatrisk.com"/>
   ("http://www.bonnerandpartners.com/feed/" finance) ;;<outline type="rss" text="Bonner &amp; Partners" title="Bonner &amp; Partners" xmlUrl="http://www.bonnerandpartners.com/feed/" htmlUrl="https://bonnerandpartners.com"/>
   ("http://cssanalytics.wordpress.com/feed/" finance) ;;<outline type="rss" text="CSSA" title="CSSA" xmlUrl="http://cssanalytics.wordpress.com/feed/" htmlUrl="https://cssanalytics.wordpress.com"/>
   ("https://www.youtube.com/feeds/videos.xml?channel_id=UC8Vq8rpqluEF07NSt9ipCkQ" finance) ;;<outline type="rss" text="The Solari Report | Catherine Austin Fitts" title="The Solari Report | Catherine Austin Fitts" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UC8Vq8rpqluEF07NSt9ipCkQ" htmlUrl="https://www.youtube.com/channel/UC8Vq8rpqluEF07NSt9ipCkQ"/>
   ("http://marketmovers.blogspot.com/feeds/posts/default?alt=rss" finance) ;;<outline type="rss" text="Trade ideas" title="Trade ideas" xmlUrl="http://marketmovers.blogspot.com/feeds/posts/default?alt=rss" htmlUrl="https://www.trade-ideas.com"/>
   ("http://mises.org/dailyarticles.xml" finance) ;;<outline type="rss" text="Mises Institute" title="Mises Institute" xmlUrl="http://mises.org/dailyarticles.xml" htmlUrl="https://mises.org/"/>
   ("http://jonathankinlay.com/index.php/feed/" finance) ;;<outline type="rss" text="Quantitative Research And Trading" title="Quantitative Research And Trading" xmlUrl="http://jonathankinlay.com/index.php/feed/" htmlUrl="https://jonathankinlay.com/"/>
   ("https://www.aqr.com/cliffs-perspective/rss-feeds/commentary-rss-feed" finance) ;;<outline type="rss" text="Cliff's Perspective" title="Cliff's Perspective" xmlUrl="https://www.aqr.com/cliffs-perspective/rss-feeds/commentary-rss-feed" htmlUrl="https://www.aqr.com/Insights/Perspectives/RSS-Feeds/Commentary-RSS-Feed"/>
   ("http://sniperinmahwah.wordpress.com/feed/" finance) ;;<outline type="rss" text="Sniper In Mahwah &amp; friends" title="Sniper In Mahwah &amp; friends" xmlUrl="http://sniperinmahwah.wordpress.com/feed/" htmlUrl="https://sniperinmahwah.wordpress.com"/>
   ("http://www.internationalman.com/sitemap.xml" finance) ;;<outline type="rss" text="International Man" title="International Man" xmlUrl="http://www.internationalman.com/sitemap.xml" htmlUrl="http://www.internationalman.com"/>
   ("http://augmentedtrader.wordpress.com/feed/" finance) ;;<outline type="rss" text="the augmented trader" title="the augmented trader" xmlUrl="http://augmentedtrader.wordpress.com/feed/" htmlUrl="https://augmentedtrader.wordpress.com"/>
   ("http://feeds.feedburner.com/TheWholeStreet" finance) ;;<outline type="rss" text="Quantocracy, Author at Quantocracy" title="Quantocracy, Author at Quantocracy" xmlUrl="http://feeds.feedburner.com/TheWholeStreet" htmlUrl="https://quantocracy.com/author/quantadmin/"/>
   ("http://feeds.feedburner.com/QuantopianBlog" finance) ;;<outline type="rss" text="Quantopian Blog" title="Quantopian Blog" xmlUrl="http://feeds.feedburner.com/QuantopianBlog" htmlUrl="https://blog.quantopian.com"/>
   ("http://quantdare.wordpress.com/feed/" finance) ;;<outline type="rss" text="Quantdare" title="Quantdare" xmlUrl="http://quantdare.wordpress.com/feed/" htmlUrl="https://quantdare.com"/>
   ("http://www.offconvex.org/feed.xml" finance) ;;<outline type="rss" text="Off the convex path" title="Off the convex path" xmlUrl="http://www.offconvex.org/feed.xml" htmlUrl="http://offconvex.github.io/"/>

   ("http://portadaloja.blogspot.com/feeds/posts/default" finance) ;;<outline type="rss" text="portadaloja" title="portadaloja" xmlUrl="http://portadaloja.blogspot.com/feeds/posts/default" htmlUrl="https://portadaloja.blogspot.com/"/>
   ("http://oinsurgente.org/feed/" finance) ;;<outline type="rss" text="O Insurgente" title="O Insurgente" xmlUrl="http://oinsurgente.org/feed/" htmlUrl="https://oinsurgente.wordpress.com"/>
   ("http://estadosentido.blogs.sapo.pt/data/rss" finance) ;;<outline type="rss" text="Estado Sentido" title="Estado Sentido" xmlUrl="http://estadosentido.blogs.sapo.pt/data/rss" htmlUrl="https://estadosentido.blogs.sapo.pt/"/>
   ("http://delitodeopiniao.blogs.sapo.pt/data/rss" finance) ;;<outline type="rss" text="Delito de Opinião" title="Delito de Opinião" xmlUrl="http://delitodeopiniao.blogs.sapo.pt/data/rss" htmlUrl="https://delitodeopiniao.blogs.sapo.pt/"/>
   ("http://portugalcontemporaneo.blogspot.com/feeds/posts/default" finance) ;;<outline type="rss" text="portugal contemporâneo" title="portugal contemporâneo" xmlUrl="http://portugalcontemporaneo.blogspot.com/feeds/posts/default" htmlUrl="http://portugalcontemporaneo.blogspot.com/"/>
   ("http://corta-fitas.blogs.sapo.pt/data/rss" finance) ;;<outline type="rss" text="Corta-fitas" title="Corta-fitas" xmlUrl="http://corta-fitas.blogs.sapo.pt/data/rss" htmlUrl="https://corta-fitas.blogs.sapo.pt/"/>
   ("http://portugaldospequeninos.blogs.sapo.pt/data/rss" finance) ;;<outline type="rss" text="portugal dos pequeninos" title="portugal dos pequeninos" xmlUrl="http://portugaldospequeninos.blogs.sapo.pt/data/rss" htmlUrl="https://portugaldospequeninos.blogs.sapo.pt/"/>
   ("http://blasfemias.net/feed/" finance) ;;<outline type="rss" text="BLASFÉMIAS" title="BLASFÉMIAS" xmlUrl="http://blasfemias.net/feed/" htmlUrl="https://blasfemias.net"/>

   ("http://www.outsideonline.com/feeds/all.rss" sport) ;;<outline type="rss" text="Outside Magazine" title="Outside Magazine" xmlUrl="http://www.outsideonline.com/feeds/all.rss" htmlUrl="https://www.outsideonline.com/"/>
   ("http://highenoughtoseethesea.tumblr.com/rss" sport) ;;<outline type="rss" text="high enough to see the sea" title="high enough to see the sea" xmlUrl="http://highenoughtoseethesea.tumblr.com/rss" htmlUrl="https://highenoughtoseethesea.tumblr.com/"/>
   ("http://www.redbull.com/en/adventure/rss/index.rss" sport) ;;<outline type="rss" text="Red Bull International (English) Adventure - most recent stories - http://www.redbull.com/en/adventure" title="Red Bull International (English) Adventure - most recent stories - http://www.redbull.com/en/adventure" xmlUrl="http://www.redbull.com/en/adventure/rss/index.rss" htmlUrl="http://www.redbull.com/en/adventure"/>

   ("https://boriquagato.substack.com/feed/" politics) ;;<outline type="rss" text="bad cattitude" title="bad cattitude" xmlUrl="https://boriquagato.substack.com/feed/" htmlUrl="https://boriquagato.substack.com"/>
   ("http://www.lewrockwell.com/rss.xml" politics) ;;<outline type="rss" text="LewRockwell" title="LewRockwell" xmlUrl="http://www.lewrockwell.com/rss.xml" htmlUrl="https://www.lewrockwell.com/"/>
   ("https://alexepstein.substack.com/feed/" politics) ;;<outline type="rss" text="Energy Talking Points by Alex Epstein" title="Energy Talking Points by Alex Epstein" xmlUrl="https://alexepstein.substack.com/feed/" htmlUrl="https://alexepstein.substack.com"/>
   ("https://unlimitedhangout.com/feed/podcast/" politics) ;;<outline type="rss" text="Unlimited Hangout with Whitney Webb" title="Unlimited Hangout with Whitney Webb" xmlUrl="https://unlimitedhangout.com/feed/podcast/" htmlUrl="https://unlimitedhangout.com/"/>
   ("http://feeds.cato.org/Cato-at-liberty" politics) ;;<outline type="rss" text="Cato at Liberty" title="Cato at Liberty" xmlUrl="http://feeds.cato.org/Cato-at-liberty" htmlUrl="https://www.cato.org/"/>
   ("http://www.dynamist.com/rss.xml" politics) ;;<outline type="rss" text="Virginia Postrel" title="Virginia Postrel" xmlUrl="http://www.dynamist.com/rss.xml" htmlUrl="https://vpostrel.com/"/>
   ("http://libertarianhome.co.uk/feed/" politics) ;;<outline type="rss" text="Libertarian Home" title="Libertarian Home" xmlUrl="http://libertarianhome.co.uk/feed/" htmlUrl="https://libertarianhome.co.uk"/>
   ("http://tucker.liberty.me/feed/" politics) ;;<outline type="rss" text="Free the People" title="Free the People" xmlUrl="http://tucker.liberty.me/feed/" htmlUrl="https://freethepeople.org/"/>
   ("http://www.stephankinsella.com/feed/" politics) ;;<outline type="rss" text="StephanKinsella.com" title="StephanKinsella.com" xmlUrl="http://www.stephankinsella.com/feed/" htmlUrl="https://stephankinsella.com"/>
   ("https://brownstone.org/feed/" politics) ;;<outline type="rss" text="Brownstone Institute" title="Brownstone Institute" xmlUrl="https://brownstone.org/feed/" htmlUrl="https://brownstone.org/"/>
   ("https://jrnyquist.blog/feed/" politics) ;;<outline type="rss" text="J.R. Nyquist Blog" title="J.R. Nyquist Blog" xmlUrl="https://jrnyquist.blog/feed/" htmlUrl="https://jrnyquist.blog"/>
   ("http://www.corbettreport.com/feed/" politics) ;;<outline type="rss" text="The Corbett Report" title="The Corbett Report" xmlUrl="http://www.corbettreport.com/feed/" htmlUrl="https://corbettreport.com"/>
   ("https://www.youtube.com/feeds/videos.xml?channel_id=UCLvRDyn_rVvZ7RRwdcEiJGw" politics) ;;<outline type="rss" text="BestEvidence" title="BestEvidence" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UCLvRDyn_rVvZ7RRwdcEiJGw" htmlUrl="https://www.youtube.com/channel/UCLvRDyn_rVvZ7RRwdcEiJGw"/>
   ("http://news.antiwar.com/feed/" politics) ;;<outline type="rss" text="News From Antiwar.com" title="News From Antiwar.com" xmlUrl="http://news.antiwar.com/feed/" htmlUrl="https://news.antiwar.com"/>
   ("http://www.hanshoppe.com/feed/" politics) ;;<outline type="rss" text="HansHoppe.com" title="HansHoppe.com" xmlUrl="http://www.hanshoppe.com/feed/" htmlUrl="https://hanshoppe.com"/>
   ("http://www.reason.com/news/index.xml" politics) ;;<outline type="rss" text="Latest – Reason.com" title="Latest – Reason.com" xmlUrl="http://www.reason.com/news/index.xml" htmlUrl="https://reason.com"/>
   ("http://www.antiwar.com/blog/feed/" politics) ;;<outline type="rss" text="Antiwar.com Blog" title="Antiwar.com Blog" xmlUrl="http://www.antiwar.com/blog/feed/" htmlUrl="https://www.antiwar.com/blog"/>
   ("https://www.libertarianinstitute.org/articles/feed/" politics) ;;<outline type="rss" text="Featured Articles | The Libertarian Institute" title="Featured Articles | The Libertarian Institute" xmlUrl="https://www.libertarianinstitute.org/articles/feed/" htmlUrl="https://libertarianinstitute.org"/>
   ("http://freedominourtime.blogspot.com/feeds/posts/default" politics) ;;<outline type="rss" text="Pro Libertate" title="Pro Libertate" xmlUrl="http://freedominourtime.blogspot.com/feeds/posts/default" htmlUrl="http://freedominourtime.blogspot.com/"/>
   ("https://unlimitedhangout.com/feed/" politics) ;;<outline type="rss" text="Unlimited Hangout" title="Unlimited Hangout" xmlUrl="https://unlimitedhangout.com/feed/" htmlUrl="https://unlimitedhangout.com/"/>
   ("http://www.samizdata.net/blog/index.rdf" politics) ;;<outline type="rss" text="Samizdata" title="Samizdata" xmlUrl="http://www.samizdata.net/blog/index.rdf" htmlUrl="https://www.samizdata.net"/>
   ("https://www.libertarianinstitute.org/feed/" politics) ;;<outline type="rss" text="The Libertarian Institute" title="The Libertarian Institute" xmlUrl="https://www.libertarianinstitute.org/feed/" htmlUrl="https://libertarianinstitute.org"/>
   ("http://takimag.com/contributors/contributor_feed/JimGoad/205/" politics) ;;<outline type="rss" text="Taki's Magazine - Feed" title="Taki's Magazine - Feed" xmlUrl="http://takimag.com/contributors/contributor_feed/JimGoad/205/" htmlUrl="http://takimag.com/article/"/>
   ("http://davidstockmanscontracorner.com/feed/" politics) ;;<outline type="rss" text="David Stockman's Contra Corner" title="David Stockman's Contra Corner" xmlUrl="http://davidstockmanscontracorner.com/feed/" htmlUrl="https://www.davidstockmanscontracorner.com/"/>
   ("http://www.oilfieldexpat.com/?feed=rss2" politics) ;;<outline type="rss" text="The Oilfield Expat" title="The Oilfield Expat" xmlUrl="http://www.oilfieldexpat.com/?feed=rss2" htmlUrl="http://www.oilfieldexpat.com"/>
   ("https://michaelyon.com/feed/" politics) ;;<outline type="rss" text="Michael Yon" title="Michael Yon" xmlUrl="https://michaelyon.com/feed/" htmlUrl="https://michaelyon.com/"/>
   ("http://feeds.feedburner.com/takimag" politics) ;;<outline type="rss" text="Taki's Magazine" title="Taki's Magazine" xmlUrl="http://feeds.feedburner.com/takimag" htmlUrl="https://www.takimag.com"/>
   ("http://www.lewrockwell.com/blog/feed/rdf" politics) ;;<outline type="rss" text="LRC Blog Archive - LewRockwell" title="LRC Blog Archive - LewRockwell" xmlUrl="http://www.lewrockwell.com/blog/feed/rdf" htmlUrl="https://www.lewrockwell.com/lrc-blog/"/>
   ("http://feeds.feedburner.com/zerohedge/feed" politics) ;;<outline type="rss" text="ZeroHedge News" title="ZeroHedge News" xmlUrl="http://feeds.feedburner.com/zerohedge/feed" htmlUrl="https://www.zerohedge.com"/>
   ("http://original.antiwar.com/feed/" politics) ;;<outline type="rss" text="Antiwar.com" title="Antiwar.com" xmlUrl="http://original.antiwar.com/feed/" htmlUrl="https://original.antiwar.com"/>
   ("http://townhall.com/xml/columnists/author/thomassowell/" politics) ;;<outline type="rss" text="Thomas Sowell's Townhall.com Column" title="Thomas Sowell's Townhall.com Column" xmlUrl="http://townhall.com/xml/columnists/author/thomassowell/" htmlUrl="http://townhall.com/"/>
   ("https://eugyppius.substack.com/feed/" politics) ;;<outline type="rss" text="eugyppius: a plague chronicle" title="eugyppius: a plague chronicle" xmlUrl="https://eugyppius.substack.com/feed/" htmlUrl="https://www.eugyppius.com"/>
   ("https://off-guardian.org/feed/" politics) ;;<outline type="rss" text="OffGuardian" title="OffGuardian" xmlUrl="https://off-guardian.org/feed/" htmlUrl="https://off-guardian.org"/>
   ("https://www.youtube.com/feeds/videos.xml?channel_id=UC8Vq8rpqluEF07NSt9ipCkQ" politics) ;;<outline type="rss" text="The Solari Report | Catherine Austin Fitts" title="The Solari Report | Catherine Austin Fitts" xmlUrl="https://www.youtube.com/feeds/videos.xml?channel_id=UC8Vq8rpqluEF07NSt9ipCkQ" htmlUrl="https://www.youtube.com/channel/UC8Vq8rpqluEF07NSt9ipCkQ"/>
   ("https://laissez-faire.ch/en/rss/articles/" politics) ;;<outline type="rss" text="Laissez-faire - Articles" title="Laissez-faire - Articles" xmlUrl="https://laissez-faire.ch/en/rss/articles/" htmlUrl="https://laissez-faire.ch/"/>
   ("https://bestevidence.substack.com/feed" politics) ;;<outline type="rss" text="BestEvidence" title="BestEvidence" xmlUrl="https://bestevidence.substack.com/feed" htmlUrl="https://bestevidence.substack.com"/>
   ("https://matthewehret.substack.com/feed/" politics) ;;<outline type="rss" text="Matt Ehret's Insights" title="Matt Ehret's Insights" xmlUrl="https://matthewehret.substack.com/feed/" htmlUrl="https://matthewehret.substack.com"/>
   ("http://liberty.me/feed/" politics) ;;<outline type="rss" text="Free the People" title="Free the People" xmlUrl="http://liberty.me/feed/" htmlUrl="https://freethepeople.org/"/>
   ("http://www.theburningplatform.com/?feed=rss2" politics) ;;<outline type="rss" text="The Burning Platform" title="The Burning Platform" xmlUrl="http://www.theburningplatform.com/?feed=rss2" htmlUrl="https://www.theburningplatform.com"/>
   ("http://www.tomwoods.com/feed/" politics) ;;<outline type="rss" text="Tom Woods" title="Tom Woods" xmlUrl="http://www.tomwoods.com/feed/" htmlUrl="https://tomwoods.com"/>
   ("https://laissez-faire.ch/en/rss/blog/" politics) ;;<outline type="rss" text="Laissez-faire - Blog" title="Laissez-faire - Blog" xmlUrl="https://laissez-faire.ch/en/rss/blog/" htmlUrl="https://laissez-faire.ch/"/>
   )
 )
