;;; godoctor-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from godoctor.el

(autoload 'godoctor-rename "godoctor" "\


(fn &optional DRY-RUN)" t)
(autoload 'godoctor-rename-dry-run "godoctor" nil t)
(autoload 'godoctor-extract "godoctor" "\


(fn &optional DRY-RUN)" t)
(autoload 'godoctor-extract-dry-run "godoctor" nil t)
(autoload 'godoctor-toggle "godoctor" "\


(fn &optional DRY-RUN)" t)
(autoload 'godoctor-toggle-dry-run "godoctor" nil t)
(autoload 'godoctor-godoc "godoctor" "\


(fn &optional DRY-RUN)" t)
(autoload 'godoctor-godoc-dry-run "godoctor" nil t)
(autoload 'godoctor-set-scope "godoctor" "\
Set the scope for the godoctor, prompting the user to edit the previous scope.

The scope restricts analysis to the specified packages.
Its value is a comma-separated list of patterns of these forms:
	golang.org/x/tools/cmd/guru     # a single package
	golang.org/x/tools/...          # all packages beneath dir
	...                             # the entire workspace.

A pattern preceded by '-' is negative, so the scope
	encoding/...,-encoding/xml
matches all encoding packages except encoding/xml." t)
(register-definition-prefixes "godoctor" '("godoctor-"))

;;; End of scraped data

(provide 'godoctor-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; godoctor-autoloads.el ends here
